fakecsv/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from account.views import LoginUser, logout_view

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('admin/', admin.site.urls),

    path('', include('user_app.urls', namespace='user_app'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_app/urls.py
from django.urls import path
from .views import SchemasView, SchemeDetailView, NewSchemaView, EditSchemaView, delete_schema, delete_column

app_name = 'user_app'

urlpatterns = [
    path('', SchemasView.as_view(), name='schemas'),
    path('new-schema', NewSchemaView.as_view(), name='new_schema'),
    path('scheme/<pk>', SchemeDetailView.as_view(), name='scheme'),
    path('scheme/<pk>/update', EditSchemaView.as_view(), name='update_schema'),
    path('scheme/<pk>/delete', delete_schema, name='delete_schema'),
    path('scheme/delete-column/<pk>', delete_column, name='delete_column')
]

user_app/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


class Type(models.Model):
    name = models.CharField(max_length=15, verbose_name='Name')
    from_range = models.BooleanField(default=False, verbose_name='View range: From')
    to_range = models.BooleanField(default=False, verbose_name='View range: To')

    class Meta:
        ordering = ('name', )

    def __str__(self):
        return self.name


class Column(models.Model):
    name = models.CharField(max_length=15, verbose_name='Name')
    type = models.ForeignKey(Type, on_delete=models.CASCADE, related_name='type', verbose_name='Type')
    schema = models.ForeignKey('Schema', on_delete=models.CASCADE, verbose_name='Schema')
    from_range = models.IntegerField(null=True, blank=True, verbose_name='Range: From')
    to_range = models.IntegerField(null=True, blank=True, verbose_name='Range: To')
    order = models.IntegerField(verbose_name='Order')

    class Meta:
        ordering = ('order', )

    def __str__(self):
        return self.name


class Schema(models.Model):
    COLUMN_SEPARATOR = [
        (',', 'Comma'),
        (';', 'Semicolon')
    ]

    STRING_CHARACTER = [
        ('\"', 'Double-quote'),
        ('\'', 'Quote')
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user', null=True, verbose_name='User')
    name = models.CharField(max_length=25, verbose_name='Name')
    column_separator = models.CharField(max_length=1, choices=COLUMN_SEPARATOR, verbose_name='Column separator')
    string_character = models.CharField(max_length=1, choices=STRING_CHARACTER, verbose_name='String character')
    modified = models.DateTimeField(auto_now=True, verbose_name='Modified')
    
    class Meta:
        ordering = ('id', )

    def __str__(self):
        return self.name


class FileCSV(models.Model):
    def upload_file(instance, filename):
        _now = datetime.now()

        return f'{instance.user.username}/{_now.year}/{_now.month}/{_now.day}/{filename}'


    schema = models.ForeignKey(Schema, on_delete=models.CASCADE, verbose_name='Schema')
    status = models.BooleanField(default=False, verbose_name='Status')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Created')
    file = models.FileField(upload_to=upload_file, verbose_name='File')

    class Meta:
        ordering = ('status', )

    def __str__(self):
        return f'{self.created} - {self.schema}'

user_app/forms.py
from django import forms
from django.forms import inlineformset_factory
from .models import Schema, Column, Type


class SchemaForm(forms.ModelForm):
    COLUMN_SEPARATOR = [
        (',', 'Comma'),
        (';', 'Semicolon')
    ]

    STRING_CHARACTER = [
        ('\"', 'Double-quote'),
        ('\'', 'Quote')
    ]

    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    column_separator = forms.ChoiceField(choices=COLUMN_SEPARATOR, widget=forms.Select(attrs={
        'class': 'form-select',
    }))
    string_character = forms.ChoiceField(choices=STRING_CHARACTER, widget=forms.Select(attrs={
        'class': 'form-select',
    }))

    class Meta:
        model = Schema
        fields = ['name', 'column_separator', 'string_character']


class ColumnForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    type = forms.ModelChoiceField(queryset=Type.objects.all(), empty_label='--------', widget=forms.Select(attrs={
        'class': 'form-select',
    }))
    from_range = forms.IntegerField(required=False, widget=forms.NumberInput(attrs={
        'class': 'form-control',
    }))
    to_range = forms.IntegerField(required=False, widget=forms.NumberInput(attrs={
        'class': 'form-control',
    }))
    order = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'form-control',
    }))

    class Meta:
        model = Column
        fields = ['name', 'type', 'from_range', 'to_range', 'order']


ColumnFormSet = inlineformset_factory(
    Schema, Column, form=ColumnForm,
    extra=1, can_delete=True, can_delete_extra=True
)

user_app/views.py
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.shortcuts import get_object_or_404
import csv
import uuid
from .utils import generate_row
from django.conf import settings
from .models import Schema, Column, Type, FileCSV
from .forms import SchemaForm, ColumnFormSet



class SchemaInline():
    form_class = SchemaForm
    model = Schema
    template_name = "add_schema.html"

    def form_valid(self, form):
        named_formsets = self.get_named_formsets()
        if not all((x.is_valid() for x in named_formsets.values())):
            return self.render_to_response(self.get_context_data(form=form))

        if not self.object:
            Schema.objects.create(user=self.request.user, **form.cleaned_data)
        else:
            self.object = form.save()

        for name, formset in named_formsets.items():
            formset_save_func = getattr(self, 'formset_{0}_valid'.format(name), None)
            if formset_save_func is not None:
                formset_save_func(formset)
            else:
                formset.save()
        return redirect('user_app:schemas')

    def formset_column_valid(self, formset):
        columns = formset.save(commit=False)
        for obj in formset.deleted_objects:
            obj.delete()
        for column in columns:
            column.schema = self.object
            column.save()


class SchemasView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    template_name = 'schemas.html'
    context_object_name = 'schemas'
    allow_empty = True

    def get_queryset(self):
        return Schema.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class SchemeDetailView(LoginRequiredMixin, DetailView):
    login_url = '/login/'
    template_name = 'schema.html'
    model = Schema
    context_object_name = 'scheme'
    queryset = Schema.objects.all()        

    def get(self, request, *args, **kwargs):
        if self.request.GET.get('rows'):
            rows = int(self.request.GET['rows'])
            columns = Column.objects.filter(schema=self.get_object())
            
            fieldnames = [column.name for column in columns]
            file_name = f'{self.get_object().user}-{self.get_object().name}-{uuid.uuid4()}.csv'

            with open(f'{settings.MEDIA_ROOT}/{file_name}', 'w') as file:
                writer = csv.DictWriter(file, fieldnames=fieldnames)
                writer.writeheader()
                for _ in range(rows):
                    row = generate_row(columns)
                    writer.writerow(row)

            FileCSV.objects.create(schema=self.get_object(), status=True, file=f'{settings.MEDIA_ROOT}/{file_name}')

            return redirect('user_app:scheme', pk=self.get_object().pk)

        return super().get(request, *args, **kwargs)
        

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['columns'] = Column.objects.filter(schema=self.get_object())
        context['csv_files'] = FileCSV.objects.filter(schema=self.get_object()) 
        return context


class NewSchemaView(LoginRequiredMixin, SchemaInline, CreateView):
    login_url = '/login/'

    def get_context_data(self, **kwargs):
        ctx = super(NewSchemaView, self).get_context_data(**kwargs)
        ctx['types'] = Type.objects.all()
        ctx['named_formsets'] = self.get_named_formsets()
        return ctx

    def get_named_formsets(self):
        if self.request.method == "GET":
            return {
                'columns': ColumnFormSet(prefix='columns'),
            }
        else:
            return {
                'columns': ColumnFormSet(self.request.POST or None, self.request.FILES or None, prefix='columns'),
            }


class EditSchemaView(LoginRequiredMixin, SchemaInline, UpdateView):
    login_url = '/login/'

    def get_context_data(self, **kwargs):
        ctx = super(EditSchemaView, self).get_context_data(**kwargs)
        ctx['types'] = Type.objects.all()
        ctx['named_formsets'] = self.get_named_formsets()
        return ctx

    def get_named_formsets(self):
        return {
            'columns': ColumnFormSet(self.request.POST or None, self.request.FILES or None, instance=self.object, prefix='columns'),
        }


@login_required(login_url="/login/")
def delete_schema(request, pk):
    schema = get_object_or_404(Schema, pk=pk)
    schema.delete()
    return redirect('user_app:schemas')


@login_required(login_url="/login/")
def delete_column(request, pk):
    column = get_object_or_404(Column, pk=pk)
    column.delete()
    return redirect('user_app:update_schema', pk=column.schema.id)

user_app/templates/add_schema.html
{% extends 'base_user_app.html' %}

{% block title %}
    New schema
{% endblock %}

{% block content %}
<form method="POST" id="column_form" enctype="multipart/form-data" class="mb-3">
    {% csrf_token %}
    <div class="container mt-4">
        <div class="row">
                <div class="row">
                    <p class="col-sm-10 title">
                        New schema
                    </p>
                    <div class="col-sm-2 pt-2">
                        <button type="submit" class="btn btn-primary">
                            Submit
                        </button>
                    </div>
                </div>
                <div class="row col-lg-6">
                    {% for f in form %}
                    <div class="mb-3">
                        {{ f.label_tag }}
                        {{ f }}
                    </div>
                    {% endfor %}
                </div>
        </div>
    </div>
    <div class="container mt-3">
            <p class="col-sm-10 title">
                    Schema columns
            </p>
        {% with named_formsets.columns as formset %}
        {{ formset.management_form }}
        <script type="text/html" id="columns-template">
            <div id="columns-__prefix__" class="row mb-3 hide_all">
                    <div class="col-3">
                        Column name
                    </div>
                    <div class="col-3">
                        Type
                    </div>
                    <div class="col-1">
                        From
                    </div>
                    <div class="col-1">
                        To
                    </div>
                    <div class="col-2">
                        Order
                    </div>
            </div>
            <div id="columns-__prefix__" class="row mb-3 hide_all">
                {% with formset.empty_form.visible_fields as fields %}
                    <div class="col-3">
                        {{ fields.0 }}
                    </div>
                    <div class="col-3">
                        {{ fields.1 }}
                    </div>
                    <div class="col-1">
                        {{ fields.2 }}
                    </div>
                    <div class="col-1">
                        {{ fields.3 }}
                    </div>
                    <div class="col-1">
                        {{ fields.4 }}
                    </div>
                {% endwith %}
            </div>
        </script>
        <div id="item-columns">
            {% for forms in formset %}
                {{ forms.management_form }}
            <div id="columns-{{ forloop.counter0 }}" class="row mb-3 hide_all">
                {{ forms.id }}
                <div class="col-3">
                    Column name
                </div>
                <div class="col-3">
                    Type
                </div>
                <div class="col-1">
                    From
                </div>
                <div class="col-1">
                    To
                </div>
                <div class="col-2">
                    Order
                </div>
            </div> 
            <div id="columns-{{ forloop.counter0 }}" class="row mb-3 hide_all">
                {{ forms.id }}
                    <div class="col-3">
                        {{ forms.name }}
                    </div>
                    <div class="col-3">
                        {{ forms.type }}
                    </div>
                    <div class="col-1">
                        {{ forms.from_range }}
                    </div>
                    <div class="col-1">
                        {{ forms.to_range }}
                    </div>
                    <div class="col-1">
                        {{ forms.order }}
                    </div>
                    {% if forms.instance.pk %}
                    <div class="col-2">
                        <a href="{% url 'user_app:delete_column' forms.instance.pk %}" class="delete_link">Delete</a>
                    </div>
                    {% endif %}
            </div>
                {% endfor %}
        </div>
        <div class="row">
            <div class="col-3">
                <a href="#" id="add-columns-button" class="btn btn-primary add-columns">
                    Add column
                </a>
            </div>
        </div>
        {% endwith %}
    </div>
</form>


<script type="text/javascript">
    
</script>
{%endblock%}

user_app/templates/base_user_app.html
{% extends 'base.html' %}

{% block main %}
    {% include 'inc/_nav.html' %}

    {% block content %}
    {% endblock %}
{% endblock %}

user_app/templates/schema.html
{% extends "base_user_app.html" %}

{% block title %}
{{ scheme.name }}
{% endblock %}

{% block content %}
    <div class="container mt-3">
        <div class="row mt-4 col-lg-8">
            <p class="col-sm-3 title">
                {{ scheme.name }}
            </p>
            <div class="col-sm-3 pt-2">
            <a href="{% url 'user_app:update_schema' pk=scheme.pk %}">Edit scheme</a>
            </div>
        </div>
        <div class="row pt-2 col-lg-8">
            <table class="table table-bordered">
                <thead>
                    <tr>
                      <th scope="col-lg-2">#</th>
                      <th scope="col-lg-5">Column name</th>
                      <th scope="col-lg-5">Column type</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for column in columns %}
                    <tr>
                      <th scope="row">{{ column.id }}</th>
                      <td>{{ column.name }}</td>
                      <td>{{ column.type }}</td>
                    </td>
                    </tr>
                    {% endfor %}
                  </tbody>
            </table>
        </div>
        <div class="row mt-3">
            <p class="col-sm-6 title">
                Data sets
            </p>
            <form method="GET" class="row col-sm-6">
                <div class="col-sm-2">
                    <p class="fs-4">Rows:</p>
                </div>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="rows">
                </div>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-success">
                        Generate data
                    </button>
                </div>
            </form>
        </div>
        <div class="row mt-2">
            <table class="table table-bordered">
                <thead>
                    <tr>
                      <th scope="col-lg-2">#</th>
                      <th scope="col-lg-5">Created</th>
                      <th scope="col-lg-5">Status</th>
                      <th scope="col-lg-5">Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for file in csv_files %}
                    <tr>
                      <th scope="row">{{ file.id }}</th>
                      <td>{{ file.created|date:'Y-m-d' }}</td>
                      <td>
                        {% if file.file %}
                        <span class="status-ready">Ready</span>
                        {% else %}
                        <span class="status-processing">Processing</span>
                        {% endif %}
                      </td>
                      <td>
                        {% if file.file %}
                        <a href='{{ file.file.url }}'>
                          Download
                        </a>
                        {% endif %}
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
            </table>
        </div>
    </div>
{% endblock%}

user_app/templates/schemas.html
{% extends 'base_user_app.html' %}

{% block title %}Schemas{% endblock %}

{% block content %}
    <div class="container">
        <div class="row mt-4 col-lg-8">
            <p class="col-sm-10 title">
                Data schemas
            </p>
            <div class="col-sm-2 pt-2">
            <a href="{% url 'user_app:new_schema' %}" class="btn btn-success">New schema</a>
            </div>
        </div>
        <div class="row pt-2 col-lg-8">
            <table class="table table-bordered">
                <thead>
                    <tr>
                      <th scope="col-lg-3">#</th>
                      <th scope="col-lg-3">Title</th>
                      <th scope="col-lg-3">Modified</th>
                      <th scope="col-lg-3">Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for schema in schemas %}
                    <tr>
                      <th scope="row">{{ schema.id }}</th>
                      <td>
                        <a href="{% url 'user_app:scheme' pk=schema.pk %}">
                          {{ schema.name }}
                        </a>
                      </td>
                      <td>{{ schema.modified|date:'Y-m-d' }}</td>
                      <td>
                        <a href="{% url 'user_app:update_schema' pk=schema.pk %}" class="">Edit scheme</a>
                        <a href="{% url 'user_app:delete_schema' pk=schema.pk %}" class="delete_link">Delete</a>
                    </td>
                    </tr>
                    {% endfor %}
                  </tbody>
            </table>
        </div>
    </div>
{% endblock %}