fakecsv/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from account.views import LoginUser, logout_view

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('admin/', admin.site.urls),

    path('', include('user_app.urls', namespace='user_app'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_app/urls.py
from django.urls import path
from .views import SchemasView, SchemeDetailView, NewSchemaView, EditSchemaView, delete_schema, delete_column

app_name = 'user_app'

urlpatterns = [
    path('', SchemasView.as_view(), name='schemas'),
    path('new-schema', NewSchemaView.as_view(), name='new_schema'),
    path('scheme/<pk>', SchemeDetailView.as_view(), name='scheme'),
    path('scheme/<pk>/update', EditSchemaView.as_view(), name='update_schema'),
    path('scheme/<pk>/delete', delete_schema, name='delete_schema'),
    path('scheme/delete-column/<pk>', delete_column, name='delete_column')
]

templates/inc/_nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">FakeCSV</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'user_app:schemas' %}">Schemas</a>
          </li>
        </ul>
        <span class="navbar-text col-lg-1">
            Hello, <b>{{ user.username }}</b>
        </span>
        <span class="navbar-text">
            <a href="{% url 'logout' %}">Logout</a>
        </span>
      </div>
    </div>
  </nav>